
[build.environment]
  NPM_VERSION = "6.14.8"
  NODE_VERSION = "12.16.3"

[build]
  publish = "docs/_build/html"
  command = "npm run build"

[context.production]
  publish = "docs/_build/html"
  command = "npm run build"

[context.deploy-preview]
  publish = "docs/_build/html"
  command = "npm run build"

[[redirects]]
  from = "/"
  to = "/docs/ras-databases/"
  status = 301
  force = false

[[redirects]]
  from = "/*"
  to = "/docs/ras-databases/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/docs/ras-databases/"
  to = "/docs/ras-databases/ras-databases-handbook/"
  status = 200
  force = false